### ISSUE TITLE
ARFF tag mismatch

### ISSUE THREAD

**Issue by tahaceritli** [haloboy777/arfftocsv#2]
Hi,

Thanks for the helpful script!

I noticed that it checks the presence of '@attribute' and '@data'. But, the ARFF format uses their uppercase versions, i.e., '@ATTRIBUTE' and '@DATA'. See the definition at https://waikato.github.io/weka-wiki/formats_and_processing/arff_stable/ (Perhaps it changed over time. I don't know.).

Anyways, I just made the small changes and created a pull request (https://github.com/haloboy777/arfftocsv/pull/3). 

Cheers,
Taha

**Comment by haloboy777** [comment]
Hi,
Sorry for delay in replying. Great catch.
I'll merge the pull request right away.

**Comment by haloboy777** [comment]
According to original spec : [https://waikato.github.io/weka-wiki/formats_and_processing/arff_stable/](https://waikato.github.io/weka-wiki/formats_and_processing/arff_stable/)

The `@RELATION`, `@ATTRIBUTE` and `@DATA` declarations are case insensitive.

**Comment by tahaceritli** [comment]
Oh, I see. Sorry for missing that.
